apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-script
data:
  CreateDB.sql: |-
    CREATE TABLE IF NOT EXISTS users (
        id bigint NOT NULL,
        email character varying COLLATE "default" NOT NULL,
        username character varying COLLATE "default" NOT NULL,
        discriminator bigint NOT NULL,
        avatar character varying COLLATE "default" NOT NULL,
        key character varying COLLATE "default",
        refresh_token character varying COLLATE "default" NOT NULL
    );