apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: vtp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtp-app
      tier: database
      track: stable
  template:
    metadata:
      labels:
        app: vtp-app
        tier: database
        track: stable
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app: vtp-app
spec:
  type: ClusterIP
  selector:
    app: vtp-app
  ports:
    - port: 5432
