apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: vtp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtp-app
      tier: database
      track: stable
  template:
    metadata:
      labels:
        app: vtp-app
        tier: database
        track: stable
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: sqlscript
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
      volumes:
        - name: sqlscript
          configMap:
            name: pg-init-script
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app: vtp-app
spec:
  type: ClusterIP
  selector:
    app: vtp-app
  ports:
    - port: 5432
