apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-script
data:
  CreateDB.sql: |- 
    CREATE TABLE IF NOT EXISTS users (
      id bigint NOT NULL,
      email character varying COLLATE "default" NOT NULL,
      username character varying COLLATE "default" NOT NULL,
      discriminator bigint NOT NULL,
      avatar character varying COLLATE "default" NOT NULL,
      key character varying COLLATE "default",
      refresh_token character varying COLLATE "default" NOT NULL,
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: sqlscript
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
      volumes:
        - name: sqlscript
          configMap:
            name: pg-init-script
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
